abandonment\abandon+ment
abasement\abase+ment
abatement\abate+ment
abbreviation\abbreviate+ion
abdication\abdicate+ion
abduction\abduct+ion
abettor\abet+or
abjuration\abjure+ation
abolition\abolish+ion
abomination\abominate+ion
abortion\abort+ion
abrasion\abrade+ion
abridgment\abridge+ment
abrogation\abrogate+ion
absolution\absolve+ution
absorption\absorb+ion
abstainer\abstain+er
abstention\abstain+ion
acceleration\accelerate+ion
accelerator\accelerate+or
acceptance\accept+ance
acceptation\accept+ation
accession\accede+ion
accommodation\accommodate+ion
accomplishment\accomplish+ment
accordance\accord+ance
accordion\accord+ion
accountant\account+ant
accretion\accrete+ion
accumulation\accumulate+ion
accumulator\accumulate+or
accusation\accuse+ation
accuser\accuse+er
achievement\achieve+ment
acquirement\acquire+ment
acquisition\acquire+ition
action\act+ion
actor\act+or
adaptation\adapt+ation
adapter\adapt+er
addiction\addict+ion
addition\add+ition
addressee\address+ee
adhesion\adhere+ion
adjournment\adjourn+ment
adjudication\adjudicate+ion
adjudicator\adjudicate+or
adjuration\adjure+ation
adjuster\adjust+er
adjustment\adjust+ment
admiration\admire+ation
admirer\admire+er
admission\admit+ion
admittance\admit+ance
admonition\admonish+ion
adoration\adore+ation
adorer\adore+er
adornment\adorn+ment
adulation\adulate+ion
adulator\adulate+or
adumbration\adumbrate+ion
advancement\advance+ment
advantage\advance+age
advertisement\advertise+ment
advertiser\advertise+er
adviser\advise+er
aeration\aerate+ion
affectation\affect+ation
affection\affect+ion
affiliation\affiliate+ion
affliction\afflict+ion
agglomeration\agglomerate+ion
aggression\aggress+ion
aggressor\aggress+or
agitation\agitate+ion
agitator\agitate+or
agreement\agree+ment
ailment\ail+ment
alignment\align+ment
allegation\allege+ation
alleviation\alleviate+ion
alliance\ally+ance
alliteration\alliterate+ion
allocation\allocate+ion
allowance\allow+ance
allurement\allure+ment
alteration\alter+ation
altercation\altercate+ion
amazement\amaze+ment
amelioration\ameliorate+ion
amendment\amend+ment
amortization\amortize+ation
amputation\amputate+ion
amputee\amputate+ee
amusement\amuse+ment
animadversion\animadvert+ion
annexation\annex+ation
annihilation\annihilate+ion
announcement\announce+ment
announcer\announce+er
annoyance\annoy+ance
annunciation\announce+ation
anointment\anoint+ment
anticipation\anticipate+ion
appearance\appear+ance
appeasement\appease+ment
appendage\append+age
applause\applaud+se
appliance\apply+ance
applicant\apply+ant
application\apply+ation
appointee\appoint+ee
appointment\appoint+ment
apposition\appose+ition
appraisal\appraise+al
appraiser\appraise+er
appreciation\appreciate+ion
apprehension\apprehend+ion
approbation\approbate+ion
approval\approve+al
arbitrament\arbitrate+ment
arbitration\arbitrate+ion
arbitrator\arbitrate+or
argument\argue+ment
armour\arm+our
arraignment\arraign+ment
arrangement\arrange+ment
arrester\arrest+er
arrival\arrive+al
articulation\articulate+ion
ascension\ascend+ion
aspersion\asperse+ion
aspirant\aspire+ant
aspiration\aspire+ation
assailant\assail+ant
assayer\assay+er
assemblage\assemble+age
assembly\assemble+y
assertion\assert+ion
assessment\assess+ment
assessor\assess+or
asseveration\asseverate+ion
assistance\assist+ance
assistant\assist+ant
association\associate+ion
assortment\assort+ment
assumption\assume+ion
astonishment\astonish+ment
atonement\atone+ment
attachment\attach+ment
attacker\attack+er
attainment\attain+ment
attention\attend+ion
attenuation\attenuate+ion
attestation\attest+ation
attorney\attorn+ey
attraction\attract+ion
augmentation\augment+ation
auscultation\auscultate+ion
automation\automate+ion
avenger\avenge+er
avoidance\avoid+ance
babbler\babble+er
bafflement\baffle+ment
baker\bake+er
bakery\bake+ery
banger\bang+er
banishment\banish+ment
barker\bark+er
barterer\barter+er
bearer\bear+er
beater\beat+er
beatification\beatify+ation
beggar\beg+ar
beginner\begin+er
behaviour\behave+our
beholder\behold+er
believer\believe+er
belongings\belong+s
bent\bend+t
bereavement\bereave+ment
betrayal\betray+al
betrayer\betray+er
better\bet+er
bewilderment\bewilder+ment
bidder\bid+er
binder\bind+er
bindery\bind+ery
birth\bear+th
bisection\bisect+ion
blasphemer\blaspheme+er
bleacher\bleach+er
bleeder\bleed+er
blender\blend+er
bloater\bloat+er
blower\blow+er
bluffer\bluff+er
blunderer\blunder+er
blusterer\bluster+er
boaster\boast+er
boiler\boil+er
bombardier\bombard+ier
bombardment\bombard+ment
booster\boost+er
bootlegger\bootleg+er
boozer\booze+er
borer\bore+er
borrower\borrow+er
botcher\botch+er
bouncer\bounce+er
boundary\bound+ary
bounder\bound+er
braggart\brag+art
brawler\brawl+er
breakage\break+age
breaker\break+er
breeder\breed+er
brewer\brew+er
brewery\brew+ery
bribery\bribe+ery
broiler\broil+er
brooder\brood+er
bruiser\bruise+er
builder\build+er
bumper\bump+er
bungler\bungle+er
burglar\burgle+ar
burglary\burglar+y
burial\bury+al
burner\burn+er
busker\busk+er
buster\bust+er
buyer\buy+er
buzzer\buzz+er
cackler\cackle+er
cadger\cadge+er
cajolery\cajole+ery
caller\call+er
cancellation\cancel+ation
cantonment\canton+ment
capitulation\capitulate+ion
carburettor\carburet+or
caroller\carol+er
carousal\carouse+al
carriage\carry+age
carrier\carry+er
carver\carve+er
caster\cast+er
castigation\castigate+ion
castration\castrate+ion
catcher\catch+er
catchment\catch+ment
caterer\cater+er
causation\cause+ation
caviller\cavil+er
celebrant\celebrate+ant
celebration\celebrate+ion
challenger\challenge+er
changeling\change+ling
chantry\chant+ry
charger\charge+er
chaser\chase+er
checker\check+er
chicanery\chicane+ery
choker\choke+er
chopper\chop+er
circulation\circulate+ion
circumcision\circumcise+ion
circumscription\circumscribe+ion
circumvention\circumvent+ion
citation\cite+ation
claimant\claim+ant
clanger\clang+er
clangour\clang+our
clapper\clap+er
cleanser\cleanse+er
cleavage\cleave+age
cleaver\cleave+er
climber\climb+er
clincher\clinch+er
clinker\clink+er
clipper\clip+er
clippie\clip+ie
coagulant\coagulate+ant
coagulation\coagulate+ion
cobbler\cobble+er
coercion\coerce+ion
cogitation\cogitate+ion
cohesion\cohere+ion
collation\collate+ion
collection\collect+ion
collector\collect+or
collision\collide+ion
collusion\collude+ion
combatant\combat+ant
combination\combine+ation
combustion\combust+ion
comer\come+er
comforter\comfort+er
commandant\command+ant
commander\command+er
commandment\command+ment
commemoration\commemorate+ion
commencement\commence+ment
commendation\commend+ation
commentator\comment+ator
commissary\commit+ary
commission\commit+ion
commitment\commit+ment
committal\commit+al
committee\commit+ee
communicant\communicate+ant
communication\communicate+ion
communion\commune+ion
commutation\commute+ation
commutator\commutate+or
commuter\commute+er
comparison\compare+ison
compensation\compensate+ion
competition\compete+ition
competitor\compete+or
compilation\compile+ation
compiler\compile+er
complainant\complain+ant
complainer\complain+er
complaint\complain+t
complication\complicate+ion
component\compose+ent
comportment\comport+ment
composer\compose+er
composition\compose+ition
compositor\compose+or
composure\compose+ure
comprehension\comprehend+ion
compulsion\compel+ion
computation\compute+ation
computer\compute+er
concatenation\concatenate+ion
concealment\conceal+ment
concentration\concentrate+ion
concept\conceive+t
conception\conceive+ion
concession\concede+ion
conciliation\conciliate+ion
conclusion\conclude+ion
concoction\concoct+ion
concussion\concuss+ion
condemnation\condemn+ation
condensation\condense+ation
condenser\condense+er
condescension\condescend+ion
condonation\condone+ation
conductance\conduct+ance
conduction\conduct+ion
conductor\conduct+or
confabulation\confabulate+ion
conference\confer+ence
conferment\confer+ment
confession\confess+ion
confessor\confess+or
confidant\confide+ant
confinement\confine+ment
confines\confine+s
confirmation\confirm+ation
confiscation\confiscate+ion
conflation\conflate+ion
confrontation\confront+ation
confusion\confuse+ion
confutation\confute+ation
congestion\congest+ion
conglomeration\conglomerate+ion
congratulation\congratulate+ion
congregation\congregate+ion
conjugation\conjugate+ion
conjunction\conjoin+ion
conjuration\conjure+ation
conjurer\conjure+er
connection\connect+ion
connivance\connive+ance
connotation\connote+ation
conqueror\conquer+or
conscription\conscript+ion
consecration\consecrate+ion
conservancy\conserve+ancy
conservation\conserve+ation
consideration\consider+ation
consignee\consign+ee
consignment\consign+ment
consignor\consign+or
consolation\console+ation
conspiracy\conspire+acy
conspirator\conspire+ator
constellation\constellate+ion
consternation\consternate+ion
constipation\constipate+ion
constitution\constitute+ion
constriction\constrict+ion
constrictor\constrict+or
construction\construct+ion
constructor\construct+or
consultant\consult+ant
consultation\consult+ation
consumer\consume+er
consumption\consume+ion
container\contain+er
containment\contain+ment
contamination\contaminate+ion
contaminator\contaminate+or
contemplation\contemplate+ion
contender\contend+er
contention\contend+ion
contestant\contest+ant
continuance\continue+ance
continuation\continue+ation
contortion\contort+ion
contraction\contract+ion
contractor\contract+or
contradiction\contradict+ion
contravention\contravene+ion
contribution\contribute+ion
contributor\contribute+or
contrivance\contrive+ance
contriver\contrive+er
controller\control+er
controversy\controvert+sy
contusion\contuse+ion
convener\convene+er
convention\convene+ion
conversation\converse+ation
conversion\convert+ion
converter\convert+er
conveyance\convey+ance
conveyer\convey+er
conviction\convict+ion
convocation\convoke+ation
convolution\convolute+ion
convulsion\convulse+ion
cooker\cook+er
cookery\cook+ery
cookie\cook+ie
copier\copy+er
copulation\copulate+ion
copyist\copy+ist
corroboration\corroborate+ion
corroborator\corroborate+or
corrosion\corrode+ion
corrugation\corrugate+ion
coruscation\coruscate+ion
counter\count+er
coverage\cover+age
cracker\crack+er
crammer\cram+er
crawler\crawl+er
creation\create+ion
creator\create+or
creature\create+ure
creeper\creep+er
cremation\cremate+ion
crematorium\cremate+orium
crepitation\crepitate+ion
crier\cry+er
crooner\croon+er
crucifixion\crucify+ion
cruiser\cruise+er
cultivation\cultivate+ion
cultivator\cultivate+or
curler\curl+er
curtailment\curtail+ment
curvature\curve+ure
cutter\cut+er
dalliance\dally+ance
damnation\damn+ation
damper\damp+er
dancer\dance+er
dawdler\dawdle+er
dealer\deal+er
debasement\debase+ment
debater\debate+er
debauchee\debauch+ee
debauchery\debauch+ery
decanter\decant+er
decapitation\decapitate+ion
deceiver\deceive+er
deception\deceive+ion
decimation\decimate+ion
decision\decide+ion
declaration\declare+ation
declension\decline+ion
declination\decline+ation
decoration\decorate+ion
decorator\decorate+or
dedication\dedicate+ion
deduction\deduce+ion
defalcation\defalcate+ion
defeatism\defeat+ism
defecation\defecate+ion
defection\defect+ion
defector\defect+or
defence\defend+ence
defendant\defend+ant
defender\defend+er
deference\defer+ence
deferment\defer+ment
defilement\defile+ment
defiler\defile+er
definition\define+ition
deflection\deflect+ion
defrayal\defray+al
defrayment\defray+ment
deification\deify+ation
dejection\deject+ion
delegation\delegate+ion
deletion\delete+ion
deliverance\deliver+ance
deliverer\deliver+er
delivery\deliver+ery
delusion\delude+ion
demeanour\demean+our
demolition\demolish+ion
demonstration\demonstrate+ion
demonstrator\demonstrate+or
demotion\demote+ion
denial\deny+al
denigration\denigrate+ion
denunciation\denounce+ation
department\depart+ment
departure\depart+ure
depiction\depict+ion
depletion\deplete+ion
deployment\deploy+ment
deportation\deport+ation
deportee\deport+ee
deportment\deport+ment
deposition\depose+ition
depositor\deposit+or
depository\deposit+ory
depravation\deprave+ation
depravity\deprave+ity
deprecation\deprecate+ion
depreciation\depreciate+ion
depredation\depredate+ion
depression\depress+ion
deputation\depute+ation
deputy\depute+y
derangement\derange+ment
derision\deride+ion
derogation\derogate+ion
descendant\descend+ant
descent\descend+t
description\describe+ion
desiccant\desiccate+ant
designer\design+er
desperation\despair+ation
destination\destine+ation
destroyer\destroy+er
destruction\destroy+ion
detachment\detach+ment
detainee\detain+ee
detection\detect+ion
detector\detect+or
detention\detain+ion
deterioration\deteriorate+ion
determinant\determine+ant
determination\determine+ation
determiner\determine+er
determinism\determine+ism
detestation\detest+ation
detonation\detonate+ion
detonator\detonate+or
devastation\devastate+ion
developer\develop+er
development\develop+ment
deviation\deviate+ion
dibber\dib+er
dictation\dictate+ion
dictator\dictate+or
differentiation\differentiate+ion
diffraction\diffract+ion
digestion\digest+ion
digger\dig+er
digression\digress+ion
dilapidation\dilapidate+ion
dilation\dilate+ion
dilution\dilute+ion
diminution\diminish+ution
diner\dine+er
dinner\dine+er
dipper\dip+er
direction\direct+ion
director\direct+or
directory\direct+ory
disbursement\disburse+ment
discernment\discern+ment
discomfiture\discomfit+ure
discrimination\discriminate+ion
discussion\discuss+ion
dismissal\dismiss+al
disparagement\disparage+ment
dispensary\dispense+ary
dispensation\dispense+ation
dispenser\dispense+er
dispersal\disperse+al
dispersion\disperse+ion
disposal\dispose+al
disposition\dispose+ition
disputant\dispute+ant
disputation\dispute+ation
disruption\disrupt+ion
dissection\dissect+ion
dissembler\dissemble+er
dissemination\disseminate+ion
dissension\dissent+ion
dissenter\dissent+er
dissipation\dissipate+ion
dissociation\dissociate+ion
dissolution\dissolve+ution
dissuasion\dissuade+ion
distension\distend+ion
distillation\distil+ation
distiller\distil+er
distillery\distil+ery
distortion\distort+ion
distraction\distract+ion
distraint\distrain+t
distribution\distribute+ion
distributor\distribute+or
disturbance\disturb+ance
divagation\divagate+ion
diver\dive+er
diversion\divert+ion
divination\divine+ation
diviner\divine+er
division\divide+ion
divisor\divide+or
divulgence\divulge+ence
dodderer\dodder+er
dodger\dodge+er
doer\do+er
doings\do+s
domination\dominate+ion
donation\donate+ion
doubter\doubt+er
dowser\dowse+er
drainage\drain+age
draper\drape+er
drapery\drape+ery
drawer\draw+er
dreamer\dream+er
dribbler\dribble+er
driftage\drift+age
drifter\drift+er
drinker\drink+er
driveller\drivel+er
driver\drive+er
dropper\drop+er
droppings\drop+s
drudgery\drudge+ery
dumper\dump+er
dweller\dwell+er
dyer\dye+er
earner\earn+er
earnings\earn+s
eater\eat+er
edification\edify+ation
edition\edit+ion
editor\edit+or
education\educate+ion
educator\educate+or
effacement\efface+ment
effusion\effuse+ion
ejaculation\ejaculate+ion
ejection\eject+ion
ejector\eject+or
elation\elate+ion
elevation\elevate+ion
elevator\elevate+or
elicitation\elicit+ation
elimination\eliminate+ion
elision\elide+ion
elopement\elope+ment
elusion\elude+ion
emaciation\emaciate+ion
emancipation\emancipate+ion
emancipator\emancipate+or
emasculation\emasculate+ion
embarrassment\embarrass+ment
embellishment\embellish+ment
embezzlement\embezzle+ment
embezzler\embezzle+er
embrocation\embrocate+ion
embroidery\embroider+ery
emissary\emit+ary
emission\emit+ion
emotion\emote+ion
employee\employ+ee
employer\employ+er
employment\employ+ment
emulation\emulate+ion
enchanter\enchant+er
enchantment\enchant+ment
enclosure\enclose+ure
encroachment\encroach+ment
endorsement\endorse+ment
endowment\endow+ment
endurance\endure+ance
engagement\engage+ment
engraver\engrave+er
enhancement\enhance+ment
enjoyment\enjoy+ment
ensilage\ensile+age
entertainer\entertain+er
entertainment\entertain+ment
enticement\entice+ment
entitlement\entitle+ment
entrance\enter+ance
entrant\enter+ant
entreaty\entreat+y
entry\enter+y
enunciation\enunciate+ion
envelopment\envelop+ment
environment\environ+ment
equipage\equip+age
equipment\equip+ment
equivocation\equivocate+ion
eradication\eradicate+ion
eradicator\eradicate+or
eraser\erase+er
erasure\erase+ure
erosion\erode+ion
eructation\eructate+ion
eruption\erupt+ion
escalation\escalate+ion
escalator\escalate+or
escapade\escape+ade
escapee\escape+ee
escapement\escape+ment
escapism\escape+ism
escapology\escape+ology
escarpment\escarp+ment
espousal\espouse+al
establishment\establish+ment
estimation\estimate+ion
estimator\estimate+or
estrangement\estrange+ment
etcher\etch+er
etiolation\etiolate+ion
evacuation\evacuate+ion
evacuee\evacuate+ee
evasion\evade+ion
eviction\evict+ion
evocation\evoke+ation
evolution\evolve+ution
exacerbation\exacerbate+ion
exaggeration\exaggerate+ion
exaltation\exalt+ation
examination\examine+ation
examiner\examine+er
exasperation\exasperate+ion
excavation\excavate+ion
excavator\excavate+or
exception\except+ion
excision\excise+ion
excitement\excite+ment
exclamation\exclaim+ation
exclusion\exclude+ion
excommunication\excommunicate+ion
excoriation\excoriate+ion
excrement\excrete+ment
excretion\excrete+ion
exculpation\exculpate+ion
execration\execrate+ion
executant\execute+ant
execution\execute+ion
executor\execute+or
exertion\exert+ion
exhalation\exhale+ation
exhaustion\exhaust+ion
exhibition\exhibit+ion
exhibitor\exhibit+or
exhilaration\exhilarate+ion
exhortation\exhort+ation
exhumation\exhume+ation
exoneration\exonerate+ion
expanse\expand+se
expansion\expand+ion
expectation\expect+ation
expectorant\expectorate+ant
expedition\expedite+ion
expenditure\expend+ure
expense\expend+se
expiation\expiate+ion
expiration\expire+ation
expiry\expire+y
explainer\explain+er
explanation\explain+ation
exploitation\exploit+ation
exploiter\exploit+er
exploration\explore+ation
explorer\explore+er
explosion\explode+ion
exportation\export+ation
exporter\export+er
exposition\expose+ition
exposure\expose+ure
expression\express+ion
expropriation\expropriate+ion
expropriator\expropriate+or
expulsion\expel+ion
extension\extend+ion
extent\extend+t
extenuation\extenuate+ion
extinguisher\extinguish+er
extirpation\extirpate+ion
extraction\extract+ion
extradition\extradite+ion
extrication\extricate+ion
extrusion\extrude+ion
exultation\exult+ation
fabrication\fabricate+ion
facilitation\facilitate+ion
failure\fail+ure
faker\fake+er
fascination\fascinate+ion
federation\federate+ion
feeder\feed+er
feeler\feel+er
fermentation\ferment+ation
fighter\fight+er
financier\finance+ier
finder\find+er
fixation\fix+ation
fixity\fix+ity
fixture\fix+ure
flapper\flap+er
flasher\flash+er
flatterer\flatter+er
flattery\flatter+ery
fledgling\fledge+ling
flier\fly+er
flipper\flip+er
flirtation\flirt+ation
floater\float+er
flotation\float+ation
fluctuation\fluctuate+ion
flunkey\flunk+ey
folder\fold+er
follower\follow+er
fomentation\foment+ation
forbearance\forbear+ance
foreclosure\foreclose+ure
forfeiture\forfeit+ure
forger\forge+er
forgery\forge+ery
forgiveness\forgive+ness
fornication\fornicate+ion
fortification\fortify+ation
fortifier\fortify+er
foundation\found+ation
founder\found+er
foundling\find+ling
foundry\found+ry
freezer\freeze+er
fructification\fructify+ation
frustration\frustrate+ion
fryer\fry+er
fucker\fuck+er
fuller\full+er
fulmination\fulminate+ion
fumbler\fumble+er
furnishings\furnish+s
fusion\fuse+ion
gainings\gain+s
gambler\gamble+er
gazer\gaze+er
generation\generate+ion
generator\generate+or
genuflection\genuflect+ion
germination\germinate+ion
gesticulation\gesticulate+ion
gibberish\gibber+ish
gilder\gild+er
girder\gird+er
girth\gird+th
giver\give+er
glazier\glaze+ier
gleaner\glean+er
gleanings\glean+s
glider\glide+er
glimmerings\glimmer+s
glissade\glide+ade
goer\go+er
goggles\goggle+s
governance\govern+ance
government\govern+ment
governor\govern+or
grabber\grab+er
graduation\graduate+ion
grater\grate+er
gratification\gratify+ation
grazier\graze+ier
grievance\grieve+ance
grinder\grind+er
griper\gripe+er
grizzly\grizzle+y
groveller\grovel+er
grower\grow+er
growler\growl+er
growth\grow+th
grumbler\grumble+er
guidance\guide+ance
gusher\gush+er
guzzler\guzzle+er
gyration\gyrate+ion
habitation\habit+ation
hallucination\hallucinate+ion
handler\handle+er
hanger\hang+er
hangings\hang+s
harassment\harass+ment
harrier\harry+er
hatchery\hatch+ery
haulage\haul+age
hauler\haul+er
haulier\haul+ier
hawker\hawk+er
healer\heal+er
health\heal+th
hearer\hear+er
hearing\hear+ing
heckler\heckle+er
helper\help+er
hesitation\hesitate+ion
hewer\hew+er
hibernation\hibernate+ion
hijacker\hijack+er
hiker\hike+er
hindrance\hinder+ance
hireling\hire+ling
hoaxer\hoax+er
holder\hold+er
hooter\hoot+er
hopper\hop+er
hoverer\hover+er
howler\howl+er
humiliation\humiliate+ion
hunter\hunt+er
hustler\hustle+er
ignition\ignite+ion
illumination\illuminate+ion
illustration\illustrate+ion
illustrator\illustrate+or
imagination\imagine+ation
imitation\imitate+ion
imitator\imitate+or
immersion\immerse+ion
immolation\immolate+ion
impairment\impair+ment
impeachment\impeach+ment
impedance\impede+ance
impediment\impede+ment
impeller\impel+er
implication\imply+ation
implosion\implode+ion
importation\import+ation
importer\import+er
importunity\importunate+ity
imposition\impose+ition
impostor\impose+or
imposture\impose+ure
impoverishment\impoverish+ment
imprecation\imprecate+ion
improvement\improve+ment
improvisation\improvise+ation
impulsion\impel+ion
incarceration\incarcerate+ion
incineration\incinerate+ion
incinerator\incinerate+or
incision\incise+ion
incisor\incise+or
incitement\incite+ment
inclination\incline+ation
inclusion\include+ion
incubation\incubate+ion
incubator\incubate+or
inculcation\inculcate+ion
incursion\incur+ion
indication\indicate+ion
indicator\indicate+or
indictment\indict+ment
inducement\induce+ment
induction\induct+ion
infection\infect+ion
inference\infer+ence
infestation\infest+ation
inflation\inflate+ion
inflection\inflect+ion
informant\inform+ant
information\inform+ation
informer\inform+er
infraction\infract+ion
infringement\infringe+ment
infusion\infuse+ion
ingestion\ingest+ion
inhabitant\inhabit+ant
inhaler\inhale+er
inheritance\inherit+ance
inhibition\inhibit+ion
injection\inject+ion
injury\injure+y
innovation\innovate+ion
innovator\innovate+or
inoculation\inoculate+ion
inquirer\inquire+er
inquiry\inquire+y
inscription\inscribe+ion
insertion\insert+ion
insinuation\insinuate+ion
inspection\inspect+ion
inspector\inspect+or
inspiration\inspire+ation
installation\install+ation
instalment\install+ment
instigation\instigate+ion
instigator\instigate+or
instillation\instil+ation
institution\institute+ion
instruction\instruct+ion
instructor\instruct+or
instrumentation\instrument+ation
insulation\insulate+ion
insulator\insulate+or
intention\intend+ion
interception\intercept+ion
interceptor\intercept+or
intercession\intercede+ion
interference\interfere+ence
interjection\interject+ion
interloper\interlope+er
interment\inter+ment
intermission\intermit+ion
internee\intern+ee
internment\intern+ment
interpellation\interpellate+ion
interpolation\interpolate+ion
interpretation\interpret+ation
interpreter\interpret+er
interrogation\interrogate+ion
interrogator\interrogate+or
interrupter\interrupt+er
interruption\interrupt+ion
intersection\intersect+ion
intervention\intervene+ion
introduction\introduce+ion
introspection\introspect+ion
introversion\introvert+ion
intruder\intrude+er
intrusion\intrude+ion
intuition\intuit+ion
inundation\inundate+ion
invader\invade+er
invasion\invade+ion
invention\invent+ion
inventor\invent+or
inventory\invent+ory
inversion\invert+ion
investigation\investigate+ion
investigator\investigate+or
investment\invest+ment
investor\invest+or
invitation\invite+ation
invocation\invoke+ation
involvement\involve+ment
irrigation\irrigate+ion
irritation\irritate+ion
isolation\isolate+ion
iteration\iterate+ion
itinerary\itinerate+ary
jabberer\jabber+er
jogger\jog+er
joiner\join+er
joinery\join+ery
joker\joke+er
jubilation\jubilate+ion
judgement\judge+ment
juggler\juggle+er
jumper\jump+er
juxtaposition\juxtapose+ition
keeper\keep+er
kicker\kick+er
kidder\kid+er
kidnapper\kidnap+er
killer\kill+er
kisser\kiss+er
knitter\knit+er
knocker\knock+er
labourer\labour+er
laceration\lacerate+ion
lactation\lactate+ion
laggard\lag+ard
lamentation\lament+ation
launderer\launder+er
launderette\launder+ette
layer\lay+er
leader\lead+er
leakage\leak+age
learner\learn+er
leavings\leave+s
legislation\legislate+ion
legislator\legislate+or
legislature\legislate+ure
lender\lend+er
lessee\lease+ee
lessor\lease+or
levitation\levitate+ion
liar\lie+ar
liberation\liberate+ion
liberator\liberate+or
licensee\license+ee
licentiate\license+ate
ligament\ligate+ment
ligature\ligate+ure
lingerer\linger+er
liquefaction\liquefy+ion
liquidation\liquidate+ion
liquidator\liquidate+or
listener\listen+er
litigant\litigate+ant
litigation\litigate+ion
liver\live+er
loafer\loaf+er
location\locate+ion
loiterer\loiter+er
looker\look+er
loppings\lop+s
loser\lose+er
lounger\lounge+er
lover\love+er
lubricant\lubricate+ant
lubrication\lubricate+ion
lubricator\lubricate+or
luggage\lug+age
maceration\macerate+ion
magnification\magnify+ation
magnifier\magnify+er
maintenance\maintain+ance
maker\make+er
malingerer\malinger+er
management\manage+ment
manager\manage+er
manipulation\manipulate+ion
manoeuvrer\manoeuvre+er
manufacturer\manufacture+er
manumission\manumit+ion
marauder\maraud+er
marcher\march+er
marriage\marry+age
mastication\masticate+ion
masturbation\masturbate+ion
matriculation\matriculate+ion
measurement\measure+ment
meddler\meddle+er
mediation\mediate+ion
mediator\mediate+or
medication\medicate+ion
meditation\meditate+ion
melioration\meliorate+ion
meliorism\meliorate+ism
mender\mend+er
menstruation\menstruate+ion
merger\merge+er
migrant\migrate+ant
migration\migrate+ion
mincer\mince+er
miner\mine+er
mitigation\mitigate+ion
mixer\mix+er
mixture\mix+ure
mocker\mock+er
mockery\mock+ery
modification\modify+ation
modifier\modify+er
modulation\modulate+ion
molestation\molest+ation
mollification\mollify+ation
moorings\moor+s
mortification\mortify+ation
mourner\mourn+er
movement\move+ment
mover\move+er
mower\mow+er
muffler\muffle+er
multiplication\multiply+ation
murderer\murder+er
mutant\mutate+ant
mutation\mutate+ion
mutilation\mutilate+ion
mutterer\mutter+er
nagger\nag+er
narration\narrate+ion
narrator\narrate+or
navigation\navigate+ion
navigator\navigate+or
negation\negate+ion
negotiation\negotiate+ion
negotiator\negotiate+or
niggler\niggle+er
nomination\nominate+ion
nominee\nominate+ee
nosher\nosh+er
notation\note+ation
nourishment\nourish+ment
obfuscation\obfuscate+ion
objection\object+ion
objector\object+or
objurgation\objurgate+ion
obligation\oblige+ation
obliteration\obliterate+ion
observation\observe+ation
observer\observe+er
obsession\obsess+ion
obstruction\obstruct+ion
occupancy\occupy+ancy
occupant\occupy+ant
occupation\occupy+ation
occupier\occupy+er
occurrence\occur+ence
offence\offend+ence
offender\offend+er
offertory\offer+ory
omission\omit+ion
operation\operate+ion
operator\operate+or
opinion\opine+ion
opponent\oppose+ent
opposition\oppose+ition
oppression\oppress+ion
oppressor\oppress+or
oration\orate+ion
orator\orate+or
ordination\ordain+ation
organization\organize+ation
organizer\organize+er
orientation\orient+ation
originator\originate+or
oscillation\oscillate+ion
oscillator\oscillate+or
osculation\osculate+ion
ossification\ossify+ation
painter\paint+er
palliation\palliate+ion
palpation\palpate+ion
palpitation\palpitate+ion
parchment\parch+ment
pardoner\pardon+er
parer\pare+er
participant\participate+ant
participation\participate+ion
passage\pass+age
pavement\pave+ment
payee\pay+ee
payer\pay+er
payment\pay+ment
pecker\peck+er
peculation\peculate+ion
peddler\peddle+er
pedlar\peddle+ar
peeler\peel+er
peelings\peel+s
peeper\peep+er
penetration\penetrate+ion
perambulation\perambulate+ion
perambulator\perambulate+or
perception\perceive+ion
percolation\percolate+ion
percolator\percolate+or
peregrination\peregrinate+ion
perforation\perforate+ion
performance\perform+ance
performer\perform+er
perisher\perish+er
perjurer\perjure+er
permeation\permeate+ion
permission\permit+ion
permutation\permute+ation
perpetration\perpetrate+ion
perpetrator\perpetrate+or
perpetuation\perpetuate+ion
persecution\persecute+ion
persecutor\persecute+or
perseverance\persevere+ance
perspiration\perspire+ation
persuasion\persuade+ion
perturbation\perturb+ation
pervasion\pervade+ion
perversion\pervert+ion
petrifaction\petrify+ion
philanderer\philander+er
picker\pick+er
pickings\pick+s
pilferage\pilfer+age
pilferer\pilfer+er
pitcher\pitch+er
player\play+er
pleasure\please+ure
plodder\plod+er
plunderer\plunder+er
plunger\plunge+er
poacher\poach+er
poker\poke+er
polisher\polish+er
pollard\poll+ard
pollster\poll+ster
pollutant\pollute+ant
pollution\pollute+ion
popper\pop+er
population\populate+ion
portage\port+age
portent\portend+t
porter\port+er
portrayal\portray+al
poser\pose+er
poseur\pose+eur
position\posit+ion
possession\possess+ion
possessor\possess+or
postponement\postpone+ment
postulant\postulate+ant
practician\practise+ian
prayer\pray+er
preacher\preach+er
precipitation\precipitate+ion
preclusion\preclude+ion
prediction\predict+ion
predictor\predict+or
pre-emption\pre-empt+ion
preemptor\pre-empt+or
preference\prefer+ence
preferment\prefer+ment
preparation\prepare+ation
preparedness\prepared+ness
prescript\prescribe+t
prescription\prescribe+ion
presentation\present+ation
presenter\present+er
preservation\preserve+ation
preserver\preserve+er
president\preside+ent
pressure\press+ure
presumption\presume+ion
pretence\pretend+ence
pretender\pretend+er
pretension\pretend+ion
prevarication\prevaricate+ion
prevaricator\prevaricate+or
preventative\prevent+ative
prevention\prevent+ion
probation\probe+ation
procedure\proceed+ure
proceeds\proceed+s
proclamation\proclaim+ation
procrastination\procrastinate+ion
procurator\procure+ator
procurement\procure+ment
procurer\procure+er
producer\produce+er
production\produce+ion
profession\profess+ion
professor\profess+or
profiteer\profit+eer
programmer\programme+er
prohibition\prohibit+ion
projection\project+ion
projector\project+or
promoter\promote+er
promotion\promote+ion
promulgation\promulgate+ion
promulgator\promulgate+or
pronouncement\pronounce+ment
pronunciation\pronounce+ation
propagation\propagate+ion
propagator\propagate+or
propeller\propel+er
propitiation\propitiate+ion
propulsion\propel+ion
prorogation\prorogue+ation
proscription\proscribe+ion
prosecution\prosecute+ion
prosecutor\prosecute+or
prospector\prospect+or
prostitution\prostitute+ion
protection\protect+ion
protector\protect+or
Protestant\protest+ant
protestation\protest+ation
protester\protest+er
protraction\protract+ion
protractor\protract+or
protrusion\protrude+ion
provider\provide+er
provision\provide+ion
provocation\provoke+ation
prowler\prowl+er
publication\publish+ation
publicist\publish+ist
publisher\publish+er
puddler\puddle+er
puffer\puff+er
pullulation\pullulate+ion
pulsation\pulsate+ion
pulverization\pulverize+ation
puncher\punch+er
punctuation\punctuate+ion
punishment\punish+ment
punster\pun+ster
purchaser\purchase+er
purgation\purge+ation
pursuance\pursue+ance
pursuer\pursue+er
purveyance\purvey+ance
purveyor\purvey+or
pusher\push+er
putrefaction\putrefy+ion
puzzlement\puzzle+ment
puzzler\puzzle+er
Quaker\quake+er
quotation\quote+ation
raillery\rail+ery
rambler\ramble+er
ramification\ramify+ation
ranger\range+er
ransomer\ransom+er
ranter\rant+er
rapist\rape+ist
ratification\ratify+ation
ratiocination\ratiocinate+ion
ravages\ravage+s
raver\rave+er
ravings\rave+s
ravishment\ravish+ment
reader\read+er
reaper\reap+er
reasoner\reason+er
rebellion\rebel+ion
recantation\recant+ation
receipt\receive+t
receiver\receive+er
reception\receive+ion
recession\recede+ion
recipient\receive+ent
reckoner\reckon+er
recognition\recognize+ition
recognizance\recognize+ance
reconcilement\reconcile+ment
reconciliation\reconcile+ation
reconnaissance\reconnoitre+ance
recorder\record+er
recovery\recover+ery
recruitment\recruit+ment
rectification\rectify+ation
rectifier\rectify+er
recuperation\recuperate+ion
redaction\redact+ion
redemption\redeem+ion
reduction\reduce+ion
reefer\reef+er
reflection\reflect+ion
reflector\reflect+or
refraction\refract+ion
refresher\refresh+er
refreshment\refresh+ment
refrigerant\refrigerate+ant
refrigeration\refrigerate+ion
refrigerator\refrigerate+or
refusal\refuse+al
refutation\refute+ation
regression\regress+ion
regulation\regulate+ion
regulator\regulate+or
regurgitation\regurgitate+ion
rehearsal\rehearse+al
reification\reify+ation
reimbursement\reimburse+ment
rejection\reject+ion
relation\relate+ion
relaxation\relax+ation
relegation\relegate+ion
remainder\remain+er
remains\remain+s
remembrance\remember+ance
remission\remit+ion
remittance\remit+ance
remonstrance\remonstrate+ance
remuneration\remunerate+ion
renegade\renege+ade
renovation\renovate+ion
renovator\renovate+or
rental\rent+al
renter\rent+er
rentier\rent+ier
renunciation\renounce+ation
repairer\repair+er
reparation\repair+ation
repatriation\repatriate+ion
repeater\repeat+er
repetition\repeat+ition
reportage\report+age
reporter\report+er
reprobation\reprobate+ion
repudiation\repudiate+ion
repulsion\repulse+ion
reputation\repute+ation
requirement\require+ment
requital\requite+al
rescuer\rescue+er
resemblance\resemble+ance
resentment\resent+ment
reservation\reserve+ation
reservist\reserve+ist
resignation\resign+ation
resister\resist+er
resistor\resist+or
resolution\resolve+ution
resonator\resonate+or
respecter\respect+er
respiration\respire+ation
respirator\respire+ator
respondent\respond+ent
response\respond+se
restoration\restore+ation
restorer\restore+er
restraint\restrain+t
restriction\restrict+ion
resumption\resume+ion
resurrection\resurrect+ion
resuscitation\resuscitate+ion
retailer\retail+er
retainer\retain+er
retaliation\retaliate+ion
retardation\retard+ation
retention\retain+ion
reticulation\reticulate+ion
retirement\retire+ment
retraction\retract+ion
retrenchment\retrench+ment
retrieval\retrieve+al
retriever\retrieve+er
retrogression\retrogress+ion
revelation\reveal+ation
reveller\revel+er
revelry\revel+ry
reverberation\reverberate+ion
reviler\revile+er
reviser\revise+er
revision\revise+ion
revival\revive+al
revocation\revoke+ation
revolution\revolt+ution
revolver\revolve+er
rider\ride+er
rigger\rig+er
ringer\ring+er
rioter\riot+er
riser\rise+er
riveter\rivet+er
roamer\roam+er
roaster\roast+er
robber\rob+er
robbery\rob+ery
rocker\rock+er
roller\roll+er
romper\romp+er
rotation\rotate+ion
rotter\rot+er
rover\rove+er
rower\row+er
ruination\ruin+ation
ruler\rule+er
rumination\ruminate+ion
runner\run+er
rustler\rustle+er
sailor\sail+or
salutation\salute+ation
sampler\sample+er
sanctification\sanctify+ation
satisfaction\satisfy+ion
saturation\saturate+ion
saunterer\saunter+er
saver\save+er
savings\save+s
saviour\save+our
scanner\scan+er
scansion\scan+ion
scavenger\scavenge+er
schemer\scheme+er
scintillation\scintillate+ion
scooter\scoot+er
scorcher\scorch+er
scourer\scour+er
scrambler\scramble+er
scraper\scrape+er
scrapings\scrape+s
scribbler\scribble+er
scrimshanker\scrimshank+er
scrounger\scrounge+er
scrubber\scrub+er
sculptor\sculpt+or
sculpture\sculpt+ure
searcher\search+er
seclusion\seclude+ion
secretion\secrete+ion
seducer\seduce+er
seduction\seduce+ion
seeker\seek+er
seepage\seep+age
seer\see+er
segregation\segregate+ion
seizure\seize+ure
selection\select+ion
selector\select+or
seller\sell+er
sender\send+er
sequestration\sequestrate+ion
servant\serve+ant
server\serve+er
servery\serve+ery
service\serve+ice
setter\set+er
severance\sever+ance
sewer\sew+er
shaker\shake+er
shaver\shave+er
shavings\shave+s
shiner\shine+er
shirker\shirk+er
shocker\shock+er
shredder\shred+er
shrinkage\shrink+age
shuffler\shuffle+er
shunter\shunt+er
shutter\shut+er
sifter\sift+er
simulation\simulate+ion
simulator\simulate+or
singer\sing+er
sinker\sink+er
sinner\sin+er
sitter\sit+er
situation\situate+ion
sizzler\sizzle+er
skimmer\skim+er
skiver\skive+er
skulker\skulk+er
slanderer\slander+er
slaughterer\slaughter+er
slayer\slay+er
sleeper\sleep+er
slipper\slip+er
slogger\slog+er
slumberer\slumber+er
smasher\smash+er
smoocher\smooch+er
smuggler\smuggle+er
snapper\snap+er
snatcher\snatch+er
sneaker\sneak+er
sneerer\sneer+er
sniffer\sniff+er
sniffler\sniffle+er
snippet\snip+et
sniveller\snivel+er
snooper\snoop+er
snorer\snore+er
snorter\snort+er
snuffer\snuff+er
soaker\soak+er
sojourner\sojourn+er
solicitation\solicit+ation
solicitor\solicit+or
solicitude\solicit+tude
solution\solve+ution
solver\solve+er
somnambulism\somnambulate+ism
soundings\sound+s
sower\sow+er
speaker\speak+er
specification\specify+ation
speculation\speculate+ion
speculator\speculate+or
speller\spell+er
spender\spend+er
spinner\spin+er
spinster\spin+ster
spittle\spit+le
splicer\splice+er
spoilage\spoil+age
spoiler\spoil+er
spoliation\spoliate+ion
spouter\spout+er
sprayer\spray+er
spreader\spread+er
sprinkler\sprinkle+er
sprinter\sprint+er
squaller\squall+er
squanderer\squander+er
squatter\squat+er
squawker\squawk+er
squeaker\squeak+er
squealer\squeal+er
squeezer\squeeze+er
squirter\squirt+er
stabber\stab+er
staggerer\stagger+er
stagnation\stagnate+ion
stalker\stalk+er
stammerer\stammer+er
stander\stand+er
starter\start+er
starvation\starve+ation
starveling\starve+ling
statement\state+ment
stayer\stay+er
stealth\steal+th
steerage\steer+age
stinger\sting+er
stinker\stink+er
stipulation\stipulate+ion
stirrer\stir+er
stockist\stock+ist
stoker\stoke+er
stoppage\stop+age
stopper\stop+er
storage\store+age
stowage\stow+age
straggler\straggle+er
strainer\strain+er
streaker\streak+er
stretcher\stretch+er
striation\striate+ion
stridulation\stridulate+ion
striker\strike+er
stripper\strip+er
striver\strive+er
stroller\stroll+er
student\study+ent
stultification\stultify+ation
stumbler\stumble+er
stunner\stun+er
stupefaction\stupefy+ion
stutterer\stutter+er
subcontractor\subcontract+or
subjugation\subjugate+ion
submission\submit+ion
subornation\suborn+ation
subscriber\subscribe+er
subscription\subscribe+ion
subsidence\subside+ence
substitution\substitute+ion
subtraction\subtract+ion
subversion\subvert+ion
succession\succeed+ion
successor\succeed+or
sucker\suck+er
suckling\suck+ling
suction\suck+ion
sufferance\suffer+ance
sufferer\suffer+er
suffocation\suffocate+ion
suffusion\suffuse+ion
suggestion\suggest+ion
superannuation\superannuate+ion
superscription\superscribe+ion
supersession\supersede+ion
supervision\supervise+ion
supervisor\supervise+or
supplanter\supplant+er
supplicant\supplicate+ant
supplication\supplicate+ion
supplier\supply+er
supporter\support+er
supposition\suppose+ition
suppression\suppress+ion
suppressor\suppress+or
suppuration\suppurate+ion
surroundings\surround+s
surveyor\survey+or
survival\survive+al
survivor\survive+or
suspender\suspend+er
suspension\suspend+ion
suspicion\suspect+ion
sustenance\sustain+ance
swaggerer\swagger+er
swallower\swallow+er
swatter\swat+er
swearer\swear+er
sweeper\sweep+er
sweepings\sweep+s
swimmer\swim+er
swindler\swindle+er
swinger\swing+er
swooper\swoop+er
swotter\swot+er
taker\take+er
takings\take+s
talker\talk+er
talkie\talk+ie
tanner\tan+er
tannery\tan+ery
tappet\tap+et
taster\taste+er
tattler\tattle+er
teacher\teach+er
teaser\tease+er
television\televise+ion
teller\tell+er
temptation\tempt+ation
tempter\tempt+er
tendency\tend+ency
tender\tend+er
tergiversation\tergiversate+ion
termination\terminate+ion
thinker\think+er
thinner\thin+er
thresher\thresh+er
thriller\thrill+er
thrower\throw+er
thruster\thrust+er
ticker\tick+er
tickler\tickle+er
tillage\till+age
tiller\till+er
tilth\till+th
tipper\tip+er
tippler\tipple+er
titillation\titillate+ion
toaster\toast+er
toddler\toddle+er
toiler\toil+er
toleration\tolerate+ion
toper\tope+er
toucher\touch+er
tracer\trace+er
tracery\trace+ery
traducer\traduce+er
trafficker\traffic+er
trailer\trail+er
trainee\train+ee
trainer\train+er
trammels\trammel+s
transcript\transcribe+t
transcription\transcribe+ion
transference\transfer+ence
transgression\transgress+ion
transgressor\transgress+or
translation\translate+ion
translator\translate+or
transliteration\transliterate+ion
transmission\transmit+ion
transmitter\transmit+er
transmogrification\transmogrify+ation
transmutation\transmute+ation
transpiration\transpire+ation
transportation\transport+ation
transporter\transport+er
traveller\travel+er
trawler\trawl+er
treater\treat+er
treatise\treat+ise
treatment\treat+ment
trespasser\trespass+er
trial\try+al
trickster\trick+ster
trier\try+er
trotter\trot+er
tucker\tuck+er
tumbler\tumble+er
turner\turn+er
twirler\twirl+er
twister\twist+er
twitcher\twitch+er
twitterer\twitter+er
typist\type+ist
ululation\ululate+ion
undulation\undulate+ion
unity\unit+y
upholsterer\upholster+er
upholstery\upholster+ery
usage\use+age
user\use+er
usurpation\usurp+ation
usurper\usurp+er
utilization\utilize+ation
utterance\utter+ance
vacation\vacate+ion
vacillation\vacillate+ion
variation\vary+ation
variety\vary+ety
vaulter\vault+er
vaunter\vaunt+er
vegetation\vegetate+ion
vendee\vend+ee
vendor\vend+or
veneration\venerate+ion
vengeance\venge+ance
ventilation\ventilate+ion
ventilator\ventilate+or
venturer\venture+er
verification\verify+ation
vexation\vex+ation
vibraphone\vibrate+phone
vibration\vibrate+ion
vibrator\vibrate+or
victualler\victual+er
victuals\victual+s
vindication\vindicate+ion
violation\violate+ion
visitant\visit+ant
visitation\visit+ation
visitor\visit+or
vitiation\vitiate+ion
vituperation\vituperate+ion
vivisection\vivisect+ion
vociferation\vociferate+ion
wader\wade+er
waiter\wait+er
waiver\waive+er
walker\walk+er
wanderer\wander+er
wanderings\wander+s
wanker\wank+er
warbler\warble+er
warrantee\warrant+ee
warrantor\warrant+or
warranty\warrant+y
washer\wash+er
wastage\waste+age
waster\waste+er
watcher\watch+er
wearer\wear+er
weaver\weave+er
welder\weld+er
welsher\welsh+er
whacker\whack+er
whiner\whine+er
whisperer\whisper+er
whittler\whittle+er
whopper\whop+er
wielder\wield+er
wiggler\wiggle+er
winner\win+er
winnings\win+s
wiper\wipe+er
wobbler\wobble+er
wooer\woo+er
worker\work+er
workings\work+s
wrangler\wrangle+er
wrapper\wrap+er
wriggler\wriggle+er
wringer\wring+er
writer\write+er
yodeller\yodel+er
